# Setup

In [3]:
import pandas as pd
import os

import torch
from model import VAE
from utilities import load_checkpoint

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cpu

# Load data

In [4]:
data_path = '../data/Linnarsson/midbrain_scanorama_expr.csv'
data = pd.read_csv(data_path,index_col=0).T
data

,10X89_7:CTAATGGCACAACGCC,10X89_7:GCACTCTAGCAACGGT,10X89_7:TCTCATAAGCAAATCA,10X89_7:AGTCTTTCATAGACTC,10X89_7:AGTGTCATCAGTTCGA,10X89_7:CTCAGAACAGTAAGCG,10X89_7:GATGAGGCAGCTGTGC,10X89_7:GCACTCTAGTCGTACT,10X89_7:AGGTCATAGATATGGT,10X89_7:AAAGCAACATCCGCGA,...,10X302_8:TTGATGGTCTTTCCAA,10X302_8:TTGGGCGAGGGAGGAC,10X302_8:TTGGTTTGTGCCTAAT,10X302_8:TTGTTCATCCACGAAT,10X302_8:AGCTTCCAGACTTAAG,10X302_8:ATTCTTGTCAACGTGT,10X302_8:CGCAGGTGTGGATCAG,10X302_8:CGAAGTTCACAGTATC,10X302_8:GCCGATGAGATCGCCC,10X302_8:GGGTGTCCACGAAGAC
TSPAN6,-0.321850,-0.645469,1.063793,0.299839,-0.583755,0.167891,-0.172803,0.406667,0.405796,2.111291,...,0.705935,0.255506,0.170741,0.573504,0.162270,0.570000,0.994927,0.199081,0.360317,-0.131157
TNMD,-0.151038,-0.169127,-0.083728,0.224539,0.009644,-0.016382,-0.015771,-0.046833,0.079503,0.417034,...,-0.451509,-0.307508,-0.455726,0.359773,3.660582,-0.357698,-0.121234,-0.242460,-0.320416,-0.347657
FIRRM,-0.494346,-0.504340,-0.515685,-0.528414,-0.520244,-0.513360,-0.527087,-0.515166,-0.549209,-0.606225,...,0.034242,-0.077764,0.136093,-0.182495,4.828612,0.414462,-0.184161,-0.145386,0.090406,2.645792
CFH,-0.021953,-0.022282,-0.010128,0.013671,0.012908,0.009769,0.010293,0.002605,0.023690,0.012806,...,-0.028285,-0.050340,-0.044357,0.413161,-0.073413,-0.022111,-0.032360,-0.014003,0.002878,-0.032798
CFTR,0.606878,0.605988,0.461923,0.300879,0.322140,0.397768,0.356800,0.438313,0.132488,0.577829,...,-0.729164,-0.719826,-0.739695,-0.667494,-0.677319,-0.723947,-0.744946,-0.752071,-0.559695,-0.549741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
IQCJ-SCHIP1,0.419309,-0.483691,-0.116496,-0.380577,1.646913,-0.300425,0.769703,0.113653,-0.476560,-0.305104,...,-0.629865,1.359450,-0.599037,14.091822,5.558343,0.688600,2.276044,-0.701311,-0.534209,-0.692545
CFAP97D2,-0.188053,-0.196060,-0.122790,-0.042764,-0.081425,-0.081583,-0.112549,-0.106098,-0.081045,-0.008801,...,0.085799,0.035704,0.136970,0.582545,0.299001,-0.036862,2.729479,0.226417,0.112656,0.159737
CCDC195,-0.091549,-0.019435,-0.064358,0.215683,0.035183,0.053852,0.006712,0.052398,0.140365,0.170752,...,-0.092710,-0.122943,-0.095506,-0.081942,-0.093363,-0.147978,0.018932,-0.103074,-0.223582,-0.165183
EXOC3L2,-0.077684,-0.100132,-0.029124,-0.087574,-0.050514,-0.038701,-0.051609,-0.032877,-0.039087,0.018532,...,0.061507,-0.101334,0.108074,1.374663,0.016648,-0.094683,0.090833,0.036886,0.000835,-0.171196
C1orf202,-0.215652,-0.200634,-0.172734,-0.114038,-0.151084,-0.160321,-0.151925,-0.164951,-0.145150,-0.078283,...,1.881470,2.369118,0.378682,1.352526,0.096100,0.147469,0.685447,0.617847,0.318847,1.596404

In [5]:
data_path = '../data/Linnarsson/midbrain_meta.csv'
meta = pd.read_csv(data_path,index_col=0)
meta

,CellClass,CellCycleFraction,DoubletFlag,DoubletScore,Region,Subdivision,Subregion,Tissue,TopLevelCluster,TotalUMIs,...,region,donor,sample,cell_ID,OldCellID,Brain_region,Age,ct_score,ct_pseudotime,ct_num_exp_genes
10X298_6:AACGAAAGTATCGAGG,b'Neuroblast',0.004950,0,0.060000,b'Midbrain',b'Midbrain',b'Midbrain',b'Midbrain',13,2387,...,Midbrain,XDD:400,10X298_6,10X298_6:AACGAAAGTATCGAGG,b'10X298_6:AACGAAAGTATCGAGG',Midbrain,5.5,0.232319,0.767681,2126
10X298_6:AGGATAAAGAGAGAAC,b'Neuroblast',0.001761,0,0.270000,b'Midbrain',b'Midbrain',b'Midbrain',b'Midbrain',13,11719,...,Midbrain,XDD:400,10X298_6,10X298_6:AGGATAAAGAGAGAAC,b'10X298_6:AGGATAAAGAGAGAAC',Midbrain,5.5,0.385680,0.614320,2059
10X298_6:CACATGACAGAGAATT,b'Neuroblast',0.002536,0,0.120000,b'Midbrain',b'Midbrain',b'Midbrain',b'Midbrain',13,6260,...,Midbrain,XDD:400,10X298_6,10X298_6:CACATGACAGAGAATT,b'10X298_6:CACATGACAGAGAATT',Midbrain,5.5,0.345192,0.654808,1978
10X298_6:CATGAGTCAAGCGCAA,b'Neuroblast',0.000873,0,0.030000,b'Midbrain',b'Midbrain',b'Midbrain',b'Midbrain',13,4959,...,Midbrain,XDD:400,10X298_6,10X298_6:CATGAGTCAAGCGCAA,b'10X298_6:CATGAGTCAAGCGCAA',Midbrain,5.5,0.391186,0.608814,1755
10X298_6:CTAGGTAGTCGTTCAA,b'Neuroblast',0.003597,0,0.140000,b'Midbrain',b'Midbrain',b'Midbrain',b'Midbrain',13,4352,...,Midbrain,XDD:400,10X298_6,10X298_6:CTAGGTAGTCGTTCAA,b'10X298_6:CTAGGTAGTCGTTCAA',Midbrain,5.5,0.429553,0.570447,1752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10X126_3:GCTCTGTAGCCACTAT,b'Radial glia',0.003527,0,0.038462,b'Midbrain',b'Midbrain',b'Midbrain',b'Mesencephalon',39,4612,...,Midbrain,BRC2114,10X126_3,10X126_3:GCTCTGTAGCCACTAT,b'10X126_3:GCTCTGTAGCCACTAT',Midbrain,6.9,0.541259,0.458741,1950
10X126_3:GGAACTTAGTGAACGC,b'Radial glia',0.026007,0,0.076923,b'Midbrain',b'Midbrain',b'Midbrain',b'Mesencephalon',39,2536,...,Midbrain,BRC2114,10X126_3,10X126_3:GGAACTTAGTGAACGC,b'10X126_3:GGAACTTAGTGAACGC',Midbrain,6.9,0.410512,0.589488,1815
10X126_3:GTGCATATCGTTACGA,b'Radial glia',0.003635,0,0.076923,b'Midbrain',b'Midbrain',b'Midbrain',b'Mesencephalon',39,1968,...,Midbrain,BRC2114,10X126_3,10X126_3:GTGCATATCGTTACGA,b'10X126_3:GTGCATATCGTTACGA',Midbrain,6.9,0.631202,0.368798,1865
10X126_3:TCTGAGATCAAACCGT,b'Radial glia',0.002854,0,0.115385,b'Midbrain',b'Midbrain',b'Midbrain',b'Mesencephalon',39,3798,...,Midbrain,BRC2114,10X126_3,10X126_3:TCTGAGATCAAACCGT,b'10X126_3:TCTGAGATCAAACCGT',Midbrain,6.9,0.514888,0.485112,1494
10X126_3:TGACTAGTCGGTCTAA,b'Radial glia',0.004229,0,0.019231,b'Midbrain',b'Midbrain',b'Midbrain',b'Mesencephalon',39,2386,...,Midbrain,BRC2114,10X126_3,10X126_3:TGACTAGTCGGTCTAA,b'10X126_3:TGACTAGTCGGTCTAA',Midbrain,6.9,0.570741,0.429259,1780

# Load model

## Load VAE

In [6]:
input_dim = data.shape[0]
latent_dim = 8

output_dir = '../out/midbrain/'
checkpoint_name = 'vae_499.pth'

In [7]:
vae = VAE(input_dim = input_dim, 
          latent_dim = latent_dim,
          encoder_dims = [1024, 512, 256, 128],
          decoder_dims = [128, 256, 512, 1024])
vae.eval()

checkpoint_path = os.path.join(output_dir, checkpoint_name)
load_checkpoint(checkpoint_path, vae, device) + 1

vae

VAE(
  (encoder): Sequential(
    (0): Linear(in_features=4561, out_features=1024, bias=True)
    (1): ReLU()
    (2): Linear(in_features=1024, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=256, bias=True)
    (5): ReLU()
    (6): Linear(in_features=256, out_features=128, bias=True)
    (7): ReLU()
  )
  (fc_mu): Linear(in_features=128, out_features=8, bias=True)
  (fc_logvar): Linear(in_features=128, out_features=8, bias=True)
  (decoder): Sequential(
    (0): Linear(in_features=8, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=256, bias=True)
    (3): ReLU()
    (4): Linear(in_features=256, out_features=512, bias=True)
    (5): ReLU()
    (6): Linear(in_features=512, out_features=1024, bias=True)
    (7): ReLU()
    (8): Linear(in_features=1024, out_features=4561, bias=True)
  )
)

## Load Psi

In [8]:
checkpoint_name = 'vae_519_trans_op.pth'
checkpoint_path = os.path.join(output_dir, checkpoint_name)
psi = torch.load(checkpoint_path, map_location=device)['psi']
psi

tensor([[[-1.3360e-02,  6.8907e-06,  1.0330e-05, -3.3358e-06,  6.6357e-06],
         [-3.2794e-02, -2.1349e-01,  1.3143e-05, -3.0300e-02, -4.0196e-06],
         [-9.2019e-06,  3.8490e-06,  1.4448e-05,  9.9183e-02, -2.6332e-06],
         [ 8.0509e-02, -7.4039e-02, -6.4198e-06,  8.6188e-02,  7.5482e-06],
         [ 1.0442e-05, -1.7787e-07, -1.5459e-05,  1.5509e-06,  1.4809e-05],
         [-9.0087e-06, -3.3726e-02, -4.4224e-06, -3.9463e-06,  1.4153e-02],
         [ 7.3746e-03, -1.2733e-06, -1.4189e-06,  1.5150e-01,  1.2306e-01],
         [-6.5070e-06,  7.8738e-06,  1.1574e-05, -5.9832e-06, -9.6031e-06]],

        [[ 3.1223e-06,  1.3710e-02,  2.3063e-06,  3.8543e-06, -3.1728e-02],
         [ 7.0484e-06, -2.2897e-06,  1.2156e-06, -6.0215e-07,  3.6258e-06],
         [ 1.0686e-01, -3.0815e-06,  1.9914e-06, -2.1179e-06,  3.6460e-02],
         [ 2.1061e-03, -1.0230e-05, -1.1114e-06, -4.1115e-06, -6.0061e-04],
         [-4.7957e-06, -3.5764e-06,  8.6635e-03,  2.5705e-02, -3.9178e-06],
         [-5.9752e-02,  2.5570e-07,  1.5103e-06,  2.4556e-03, -4.6306e-07],
         [-4.4298e-06, -6.5316e-06,  1.0328e-01, -6.5024e-03,  2.4127e-02],
         [-3.2172e-06,  1.0878e-06,  1.4563e-05, -8.4012e-07,  3.9432e-06]],

        [[ 3.1696e-06, -1.0651e-02,  1.1116e-05,  9.1184e-07,  1.2934e-06],
         [ 1.1835e-05,  4.3849e-06,  6.8006e-02, -3.9720e-02,  2.4801e-06],
         [ 5.1025e-06,  3.7114e-03,  8.3779e-06,  4.4251e-02,  2.6246e-06],
         [ 1.4055e-01,  2.9255e-06,  4.1959e-06,  7.4045e-07, -4.1596e-02],
         [-1.1932e-05,  1.3344e-02,  2.0754e-06, -4.1290e-06, -3.1442e-02],
         [ 1.9207e-06,  1.3850e-06, -1.2943e-06, -4.7697e-02,  2.0846e-06],
         [ 6.6265e-06,  9.4244e-03,  6.9679e-06,  4.6726e-06,  1.6066e-02],
         [ 6.6247e-06, -5.5129e-06, -1.9673e-07,  2.7332e-06,  1.1400e-06]],

        [[-3.4061e-07, -4.5813e-06,  7.8366e-02,  1.3708e-06,  2.3055e-06],
         [-5.1246e-06, -3.5845e-06,  1.2619e-05, -1.2796e-01,  1.3473e-06],
         [-3.1861e-06, -2.3019e-06, -8.0835e-03,  3.7083e-06, -6.2330e-06],
         [-1.3065e-06,  5.9314e-06,  1.7784e-06,  4.6577e-06, -1.1186e-02],
         [-1.0523e-01,  1.0806e-05,  1.0730e-05,  1.9413e-06,  4.9819e-03],
         [-5.3331e-07, -1.6251e-06, -3.2089e-02, -2.5856e-06, -3.3872e-03],
         [-4.4193e-06,  4.4608e-06, -1.0812e-02, -1.2994e-03,  9.0658e-07],
         [ 3.7184e-06, -1.7803e-01, -5.3103e-06,  2.0416e-06, -6.2126e-06]],

        [[-1.9894e-07,  9.5974e-06, -3.3614e-06,  4.7837e-03, -1.1240e-06],
         [-3.7403e-07,  9.5907e-06,  1.1556e-06, -2.8231e-06,  2.4446e-02],
         [-7.4666e-03,  9.2291e-06,  2.2508e-06, -1.2100e-05, -5.7891e-06],
         [ 4.3668e-07,  3.1031e-02,  7.9234e-06, -2.0800e-05,  1.3461e-09],
         [ 9.1740e-02, -4.0167e-06,  8.3908e-06,  1.5541e-06, -2.4938e-02],
         [-1.0120e-01, -1.8599e-06,  1.8279e-01,  5.6915e-06, -4.8965e-06],
         [-1.1221e-06, -1.4718e-06, -6.7034e-02, -8.3664e-06,  7.5012e-02],
         [-5.4588e-02,  1.0875e-05, -7.4883e-06, -7.0252e-06, -7.4790e-06]],

        [[-2.1853e-01,  2.2008e-03,  6.6814e-06,  1.3659e-05, -4.7630e-02],
         [ 9.2781e-02, -9.1475e-03,  5.9425e-06,  2.7655e-02, -5.5152e-02],
         [-2.1613e-06,  1.2291e-05, -1.3250e-07, -7.2946e-02, -1.2860e-06],
         [-9.7154e-02,  1.9222e-05,  2.5338e-05, -1.1567e-05, -5.1982e-06],
         [-1.2193e-02,  5.4569e-02, -7.4189e-02,  1.5412e-02,  6.1691e-06],
         [ 4.6361e-06, -2.7730e-06,  3.1306e-02,  9.8348e-03,  1.8068e-02],
         [-8.5607e-06,  7.2815e-06,  3.2931e-06, -8.4374e-06, -1.0325e-05],
         [ 3.8719e-07, -3.1608e-06, -2.2724e-02,  3.4055e-03, -4.7297e-02]],

        [[ 9.0539e-06,  2.3064e-02, -3.0637e-02, -7.8304e-06, -1.2017e-02],
         [-3.0205e-03,  3.2426e-06, -1.6712e-01, -5.5060e-06, -1.0439e-01],
         [-1.7928e-02,  5.5021e-06,  6.8570e-06,  2.2737e-02, -1.4524e-02],
         [-3.7509e-03, -2.8445e-03,  5.6629e-06,  1.8944e-02, -1.4644e-06],
         [-8.4698e-06, -1.2435e-05,  1.4670e-06, -6.3736e-06,  9.1996e-06],
         [-2.7234e-02,  3.0559e-06, -7.3513e-06,  7.3522e-02,  8.2254e-06],
         [ 4.7770e-06,  2.6116e-06,  1.0264e-05, -1.3184e-05,  1.5362e-05],
         [ 4.4122e-06, -1.0300e-01,  3.3832e-02, -7.7745e-03,  6.8123e-02]],

        [[-3.6001e-06, -1.3272e-05,  1.3990e-05,  8.5913e-06,  1.1298e-05],
         [-1.2078e-05, -1.4458e-05,  7.2433e-06, -3.9230e-02,  1.5822e-05],
         [-1.1474e-01, -1.2742e-05,  7.9042e-06,  1.2161e-05, -1.2670e-02],
         [ 2.6238e-02,  8.1220e-02,  5.2271e-07,  4.8060e-02,  5.1054e-06],
         [ 1.8131e-02,  7.2941e-06, -5.9506e-02, -1.8266e-05,  4.3109e-03],
         [-2.9775e-06,  6.8999e-07,  1.2401e-06,  4.9105e-06,  1.0289e-05],
         [-1.0273e-06, -7.0547e-06,  3.1116e-06,  9.8443e-06, -5.7877e-03],
         [-5.9047e-06, -9.1235e-02,  7.9221e-06,  8.1341e-06, -8.6918e-02]]])

# Analysis

In [9]:
with torch.no_grad():
    z0, mu, _ = vae.Encode(torch.Tensor(data.T.values))

In [10]:
z1 = torch.einsum('mik, bk -> mbi', torch.matrix_exp(psi.permute(2,0,1)), z0)

In [11]:
velocity = z1 - z0

In [12]:
import anndata
import numpy as np
adata = anndata.AnnData(np.array(mu))
adata.obs = meta
adata

AnnData object with n_obs × n_vars = 21940 × 8
    obs: 'CellClass', 'CellCycleFraction', 'DoubletFlag', 'DoubletScore', 'Region', 'Subdivision', 'Subregion', 'Tissue', 'TopLevelCluster', 'TotalUMIs', 'organism_ontology_term_id', 'disease_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'assay_ontology_term_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'donor_id', 'suspension_type', 'dissection', 'total_UMIs', 'sample_id', 'cluster_id', 'class', 'region', 'donor', 'sample', 'cell_ID', 'OldCellID', 'Brain_region', 'Age', 'ct_score', 'ct_pseudotime', 'ct_num_exp_genes'

In [13]:
for i in range(psi.shape[-1]):
   z1_key = f'z1_psi{i}'
   v_key = f'v_psi{i}'
   adata.layers[z1_key] = np.array(z1[i, :, :])
   adata.layers[v_key] = np.array(velocity[i, :, :])

In [14]:
adata.obsm['X_mu'] = np.array(mu)
adata.obsm['X_z0'] = np.array(z0)

In [2]:
import scanpy as sc

In [15]:
sc.pp.neighbors(adata,use_rep='X_z0', random_state=0,key_added='z0')
sc.tl.umap(adata,neighbors_key='z0')
adata.obsm['X_umap_z0'] = adata.obsm['X_umap'].copy()
del adata.obsm['X_umap']
sc.pl.embedding(adata,color=['class','Age'],basis ='umap_z0')

OMP: Info #271: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

: